Feat/13 month calendar week number
IOMechs/angular-year-calendar pull request #53
Opened 2024-03-25 10:08 UTC by tahamohsini

2024-03-25 16:45 UTC, AhsanAyaz requested changes
Looks good. Just added a few comments

2024-03-25 16:45 UTC, AhsanAyaz commented on projects/angular-year-calendar/src/lib/pipes/week-number/week-number.pipe.ts
> +      const diff = (date.getTime() - firstWeekFirstDate.getTime()) / 86400000;
Can we move this constant into a `const` variable to show that this number means?

2024-03-25 16:45 UTC, AhsanAyaz commented on projects/angular-year-calendar/src/lib/pipes/week-number/week-number.pipe.ts
> +      }
Could you add a comment right above this if condition about what this if condition means?

2024-03-25 16:45 UTC, AhsanAyaz commented on projects/angular-year-calendar/src/lib/pipes/week-number/week-number.pipe.ts
> +      const dayDiff = (nextYearFirstDate.getTime() - date.getTime()) / 86400000;
Same comment. Please move to a const

2024-03-25 16:45 UTC, AhsanAyaz commented on projects/demo/src/app/app.module.ts
> +// import { YearCalendarModule } from '@iomechs/angular-year-calendar';
I believe this needs to be reset? I.e. use the package instead of local public-api path?

2024-03-26 06:46 UTC, tahamohsini commented on projects/demo/src/app/app.module.ts
> +// import { YearCalendarModule } from '@iomechs/angular-year-calendar';
we were using the path instead of the package
updated as per your instruction

2024-03-26 08:10 UTC, AhsanAyaz requested changes

2024-03-26 08:10 UTC, AhsanAyaz commented on projects/angular-year-calendar/src/lib/pipes/week-number/week-number.pipe.ts
> +    const oneDay = 86400000; // milliseconds in a day
Can we rename this? We shouldn't need a comment to explain a variable name. The variable name should be self explanatory.

```suggestion
    const millisecondsInADay = 86400000;
```

2024-03-26 08:10 UTC, AhsanAyaz commented on projects/demo/src/app/app.module.ts
> +// import { YearCalendarModule } from "../../../angular-year-calendar/src/public-api";
We can remove this import since we're not using it.

2024-03-26 09:45 UTC, AhsanAyaz approved these changes
LGTM

2024-03-26 09:45 UTC, merged